server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/${AUTH_DB_NAME:auth_db}
    username: ${AUTH_DB_USER:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:7wxk4fGHymzwjCSTb5aViJvTI87Smk6qDDtakrcMcbgp5TJRZ+gUMtm5N5Hxp9lp}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health